# Instalando librerías python necesarias
```bash
pip install langdetect
pip install chardet
pip install beautifulsoup4
pip install lxml
pip install requests
pip install pillow
pip install pytesseract
pip install nltk
pip install scikit-learn
pip install numpy
```

In [1]:
import os
import re
import unicodedata
import numpy as np
import pandas as pd
import requests
import chardet
import nltk
import pytesseract
from PIL import Image

from bs4 import BeautifulSoup
from PIL import Image
from langdetect import detect

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import SnowballStemmer
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer

# Descarga de recursos

In [2]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to /home/rusok/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /home/rusok/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /home/rusok/nltk_data...
[nltk_data] Downloading package omw-1.4 to /home/rusok/nltk_data...


True

# Verificación de codificación

In [3]:
ruta = "archivo.txt"

In [4]:
if os.path.exists(ruta):
    with open(ruta, "rb") as f:
        resultado = chardet.detect(f.read())
        encoding = resultado["encoding"]
    
    print(f"Codificación detectada: {encoding}")
else:
    print(f"ERROR: No se encontró el archivo en: {ruta}")
    
    # Mostrar qué hay en la carpeta
    carpeta = "."
    if os.path.exists(carpeta):
        print(f"\nContenido de la carpeta '{carpeta}':")
        for archivo in os.listdir(carpeta):
            print(f"  - {archivo}")
    else:
        print(f"La carpeta '{carpeta}' tampoco existe")

with open("archivo.txt", encoding="utf-8") as f:
    texto = f.read()

Codificación detectada: utf-8


# Detección de idioma

In [5]:
texto = "Este texto está en español."

idioma = detect(texto)

print(f"Idioma detectado: {idioma}")

Idioma detectado: es


### Prueba simple


In [6]:
texto = "This text is short"

idioma = detect(texto)

print(f"Idioma detectado: {idioma}")

Idioma detectado: en


# Verificación de tamaño

In [7]:
path = "corpus.txt"

tamaño_bytes = os.path.getsize(path)
tamaño_mb = tamaño_bytes / (1024 * 1024)

print(f"Tamaño del archivo: {tamaño_mb:.2f} MB")

Tamaño del archivo: 0.00 MB


In [10]:
def formatear_tamaño(path):
    bytes_ = os.path.getsize(path)
    return {
        "Bytes": bytes_,
        "KB": bytes_ / 1024,
        "MB": bytes_ / (1024 * 1024)
    }


In [11]:

print(formatear_tamaño("corpus.txt"))

{'Bytes': 1213, 'KB': 1.1845703125, 'MB': 0.0011568069458007812}


# CARGA DE DOCUMENTOS SEGÚN FORMATO

## TXT

In [12]:
with open("texto.txt", encoding="utf-8") as f:
    texto_txt = f.read()

print(texto_txt)

La seguridad informática constituye un elemento esencial en la protección de la información digital.

Actualmente existen múltiples amenazas:

- Malware
- Phishing
- Ransomware
- Ingeniería social
- Ataques DDoS
- Robo de credenciales

Las organizaciones implementan controles de seguridad para minimizar riesgos y proteger sus activos digitales.

Entre los mecanismos más importantes se encuentran:

- Firewalls
- Sistemas IDS/IPS
- Antivirus
- Cifrado de datos
- Autenticación multifactor
- Monitoreo continuo

La minería de textos puede ayudar a detectar patrones sospechosos en reportes de seguridad y mensajes electrónicos.


## CSV

In [13]:
df = pd.read_csv("dataset.csv", encoding="utf-8")

texto_csv = " ".join(df["columna_texto"].dropna())

print(texto_csv)

La minería de datos permite descubrir patrones ocultos Python facilita el procesamiento del lenguaje natural La inteligencia artificial mejora los sistemas de análisis Las universidades utilizan bibliotecas digitales La ciberseguridad protege los activos digitales El análisis textual ayuda en la detección de amenazas Los algoritmos de aprendizaje automático procesan grandes volúmenes de información La tokenización divide el texto en unidades lingüísticas Las redes neuronales permiten automatizar tareas complejas El procesamiento de lenguaje natural analiza documentos digitales Las organizaciones monitorean correos sospechosos Los sistemas inteligentes generan reportes automatizados La minería de textos extrae conocimiento útil La protección de datos es fundamental para las empresas Los modelos predictivos ayudan en la toma de decisiones


## WEB

In [14]:
url = "https://books.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

texto_web = soup.get_text()

print(texto_web)





  


    All products | Books to Scrape - Sandbox

















Books to Scrape We love being scraped!








Home

All products









                            
                                Books
                            
                        



                            
                                Travel
                            
                        



                            
                                Mystery
                            
                        



                            
                                Historical Fiction
                            
                        



                            
                                Sequential Art
                            
                        



                            
                                Classics
                            
                        



                            
                                Philosophy
          

## Prueba RFC 6902

In [15]:
url = "https://www.rfc-editor.org/rfc/rfc6902"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

texto_web = soup.get_text()

print(texto_web)
















RFC 6902: JavaScript Object Notation (JSON) Patch

 

[RFC Home] [TEXT|PDF|HTML] [Tracker] [IPR] [Errata] [Info page]                                                                 PROPOSED STANDARD Errata ExistInternet Engineering Task Force (IETF)                     P. Bryan, Ed.
Request for Comments: 6902                                Salesforce.com
Category: Standards Track                             M. Nottingham, Ed.
ISSN: 2070-1721                                                   Akamai
                                                              April 2013


                JavaScript Object Notation (JSON) Patch

Abstract

   JSON Patch defines a JSON document structure for expressing a
   sequence of operations to apply to a JavaScript Object Notation
   (JSON) document; it is suitable for use with the HTTP PATCH method.
   The "application/json-patch+json" media type is used to identify such
   patch documents.

Status of This Memo

   This is an Interne

## ORC

###  sudo apt install tesseract-ocr
###  sudo apt install libtesseract-dev


In [16]:
from PIL import Image
import pytesseract
import re

ruta_imagen = 'documento.jpg'

try:
    # Abrir la imagen
    imagen = Image.open(ruta_imagen)
    # Extraer texto usando español e inglés
    # lang='spa' para español, 'eng' para inglés, o 'spa+eng' para ambos
    texto = pytesseract.image_to_string(imagen, lang='spa+eng')
    # Limpiar el texto (opcional)
    texto = re.sub(r'\n+', '\n', texto).strip()

    print("Texto extraído:")
    print("-" * 50)
    print(texto)
    print("-" * 50)

except FileNotFoundError:
    print(f"No se encontró la imagen en: {ruta_imagen}")
except Exception as e:
    print(f"Error al procesar: {e}")

Texto extraído:
--------------------------------------------------
Mineria de Textos
Procesamiento del Lenguaje Natural
Universidad Publica de El Alto
Python y Ciencia de Datos
Ciberseguridad y Analisis Documental
--------------------------------------------------


### Prueba rápida

In [17]:
from PIL import Image
import pytesseract
import re

ruta_imagen = 'prueba20260509.jpg'

try:
    # Abrir la imagen
    imagen = Image.open(ruta_imagen)
    # Extraer texto usando español e inglés
    # lang='spa' para español, 'eng' para inglés, o 'spa+eng' para ambos
    texto = pytesseract.image_to_string(imagen, lang='spa+eng')
    # Limpiar el texto (opcional)
    texto = re.sub(r'\n+', '\n', texto).strip()

    print("Texto extraído:")
    print("-" * 50)
    print(texto)
    print("-" * 50)

except FileNotFoundError:
    print(f"No se encontró la imagen en: {ruta_imagen}")
except Exception as e:
    print(f"Error al procesar: {e}")

Texto extraído:
--------------------------------------------------
itty a
a
5es de uso: use pelo menos uma vez ao dia apés a escovagao. Insira 0 fio tensionado,
-0 entre os dentes, de:
1 dante limpando além da linha da gengiva.
© Visite Seu dentista reguiarmente. * Nao compre se
zando com cuidado com movimentos de vai e vem, a0 redor do
‘a embalagem estiver violada.
Mantenha fora do alcance das criangas. O uso em criangas deve ser supervisionado
por
Polypropylene/polipropileno,
dulto. * Conserve em local fresco @ seco. Composigao/Composiclon/Composition:
Microcrystalline
Waxicera _microcristalina, © Aroma
{¢-Limonene/dextrolimoneno), Cl 74260/corante verde,
Prazo de Valldade (més / ano) e Lote: vide indicago na embalagem.
Instrucciones de uso: Tensar un trozo de hilo con los dedos medios de ambas manos y hacer
pasar entre los dientes y molares. * Visite a su dentista / odontélogo regularmenta Uso def
producto: Higiene Bucal. » No compre si el empaque / envase estuviera abiorto. ° Mante

# Limpieza básica

In [18]:
texto = """
Hola!!!
Este es un texto de prueba.

Visita: https://ejemplo.com
"""

texto = re.sub(r"\n", " ", texto)

texto = re.sub(
    r"[^a-zA-Z0-9áéíóúñü\s]",
    " ",
    texto
)

texto = re.sub(r"\s+", " ", texto).strip()

print(texto)

Hola Este es un texto de prueba Visita https ejemplo com


## Normalización

In [19]:
def normalize_text(texto: str) -> str:

    texto = texto.lower()

    texto = re.sub(r"[^\w\s]", " ", texto)

    texto = re.sub(r"\d+", " ", texto)

    texto = re.sub(r"\s+", " ", texto).strip()

    texto = unicodedata.normalize("NFKD", texto)

    texto = "".join(
        c for c in texto
        if not unicodedata.combining(c)
    )

    return texto


texto = "¡Minería de Textos 2025 en la UPEA!"

texto_normalizado = normalize_text(texto)

print(texto_normalizado)

mineria de textos en la upea


# Eliminación de ruido

In [20]:
texto = """
Síguenos en https://ejemplo.com
#MineriaDeTextos @usuario
"""

# Eliminar URLs
texto = re.sub(r"https?:\/\/\S+", "", texto)

# Eliminar hashtags (ej: #MineriaDeTextos)
texto = re.sub(r"#\w+", "", texto)

# Eliminar menciones (ej: @usuario)
texto = re.sub(r"@\w+", "", texto)

# Limpiar espacios extras
texto = re.sub(r"\s+", " ", texto).strip()

print(texto)

Síguenos en


# Remoción de stopwords

In [22]:
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt_tab to /home/rusok/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /home/rusok/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
texto = "Este es un ejemplo de texto para eliminar stopwords."

tokens = word_tokenize(texto.lower())

stopwords_spanish = set(
    stopwords.words("spanish")
)

tokens_sin_stop = [
    token
    for token in tokens
    if token not in stopwords_spanish
]

print(tokens_sin_stop)

['ejemplo', 'texto', 'eliminar', 'stopwords', '.']


# Tokenización

In [26]:
texto = """
La minería de textos es poderosa.
Permite extraer patrones útiles.
"""

tokens_palabras = word_tokenize(texto.lower())

tokens_oraciones = sent_tokenize(texto)

print("Tokens por palabra:")
print(tokens_palabras)

print("\nTokens por oración:")
print(tokens_oraciones)

Tokens por palabra:
['la', 'minería', 'de', 'textos', 'es', 'poderosa', '.', 'permite', 'extraer', 'patrones', 'útiles', '.']

Tokens por oración:
['\nLa minería de textos es poderosa.', 'Permite extraer patrones útiles.']


# Stemming

## Encuentra las palabras raíz

In [27]:
stemmer = SnowballStemmer("spanish")

words = [
    "corriendo",
    "corrida",
    "corredor"
]

stems = [
    stemmer.stem(word)
    for word in words
]

print(stems)

['corr', 'corr', 'corredor']


# Lematización

In [28]:
lemmatizer = WordNetLemmatizer()

words = [
    "running",
    "cars",
    "better"
]

for word in words:

    lemma = lemmatizer.lemmatize(word)

    print(f"{word} -> {lemma}")

running -> running
cars -> car
better -> better


In [29]:
lemmatizer = WordNetLemmatizer()

words = [
    "corriendo",
    "autos",
    "mejores"
]

for word in words:

    lemma = lemmatizer.lemmatize(word)

    print(f"{word} -> {lemma}")

corriendo -> corriendo
autos -> auto
mejores -> mejores


# DTM Document-Term matrix

In [31]:
corpus = [
    "la minería de textos es poderosa",
    "la minería de textos permite extraer patrones"
]

vectorizer = CountVectorizer()

dtm = vectorizer.fit_transform(corpus)

print("Vocabulario:")
print(vectorizer.get_feature_names_out())

print("\nDTM:")
print(dtm.toarray())

Vocabulario:
['de' 'es' 'extraer' 'la' 'minería' 'patrones' 'permite' 'poderosa'
 'textos']

DTM:
[[1 1 0 1 1 0 0 1 1]
 [1 0 1 1 1 1 1 0 1]]


In [32]:
tdm = dtm.T

print("TDM (término × documento):")
print(tdm.toarray())

TDM (término × documento):
[[1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]]


# Frecuencia de términos

In [33]:
frecuencia_terminos = dtm.toarray().sum(axis=0)

print("Frecuencia de términos:")
print(frecuencia_terminos)

Frecuencia de términos:
[2 1 1 2 2 1 1 1 2]
